declare module '@ckeditor/ckeditor5-editor-classic/src/classiceditor' { export default class ClassicEditor {} }

declare module '@ckeditor/ckeditor5-alignment/src/alignment' { export default class Alignment {} }
declare module '@ckeditor/ckeditor5-autoformat/src/autoformat' { export default class Autoformat {} }
declare module '@ckeditor/ckeditor5-basic-styles/src/bold' { export default class Bold {} }
declare module '@ckeditor/ckeditor5-basic-styles/src/italic' { export default class Italic {} }
declare module '@ckeditor/ckeditor5-basic-styles/src/strikethrough' { export default class Strikethrough {} }
declare module '@ckeditor/ckeditor5-basic-styles/src/underline' { export default class Underline {} }
declare module '@ckeditor/ckeditor5-core/src/plugin' { export default class Plugin {} }
declare module '@ckeditor/ckeditor5-remove-format/src/removeformat' { export default class RemoveFormat {} }
declare module '@ckeditor/ckeditor5-remove-format/src/removeformatui' { export default class RemoveFormatLinks {} }
declare module '@ckeditor/ckeditor5-essentials/src/essentials' { export default class Essentials {} }
declare module '@ckeditor/ckeditor5-font/src/fontbackgroundcolor' { export default class FontBackgroundColor {} }
declare module '@ckeditor/ckeditor5-font/src/fontcolor' { export default class FontColor {} }
declare module '@ckeditor/ckeditor5-heading/src/heading' { export default class Heading {} }
declare module '@ckeditor/ckeditor5-image/src/image' { export default class Image {} }
declare module '@ckeditor/ckeditor5-image/src/imagecaption' { export default class ImageCaption {} }
declare module '@ckeditor/ckeditor5-image/src/imagestyle' { export default class ImageStyle {} }
declare module '@ckeditor/ckeditor5-image/src/imagetoolbar' { export default class ImageToolbar {} }
declare module '@ckeditor/ckeditor5-link/src/link' { export default class Link {} }
declare module '@ckeditor/ckeditor5-list/src/list' { export default class List {} }
declare module '@ckeditor/ckeditor5-media-embed/src/mediaembed' { export default class MediaEmbed {} }
declare module '@ckeditor/ckeditor5-media-embed/src/mediaembedtoolbar' { export default class MediaEmbedToolbar {} }
declare module '@ckeditor/ckeditor5-paragraph/src/paragraph' { export default class Paragraph {} }
declare module '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice' { export default class PasteFromOffice {} }
declare module '@ckeditor/ckeditor5-table/src/table' { export default class Table {} }
declare module '@ckeditor/ckeditor5-table/src/tabletoolbar' { export default class TableToolbar {} }
